=== willrudolph/sdj-esm/src/schema/sdj-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://willrudolph.com/schema/sdj-schema.json",
  "type": "object",
  "title": "SDJ Schema",
  "required": [
    "$id",
    "description",
    "sdInfo",
    "data"
  ],
  "properties": {
    "$id": {
      "type": "string",
      "title":"Sdj Schema Reference"
    },
    "sdInfo": {
      "type": "object",
      "$ref": "#/$defs/info",
      "title": "File name, uniqId, created/modified for Json File."
    },
    "description": {
      "type": "object",
      "$ref": "#/$defs/description",
      "title": "Self Description Object for SDJ file."
    },
    "data": {
      "type": "array",
      "default": [],
      "title": "The top level data objects",
      "items": {
        "$ref": "#/$defs/data"
      }
    }
  },
  "additionalProperties": false,
  "$defs": {
    "description": {
      "type": "object",
      "description": "Description information for SDJ data",
      "properties": {
        "sdInfo": {
          "type": "object",
          "$ref": "#/$defs/info",
          "title": "Name, uniqId, created/modified for SDJ Description"
        },
        "items": {
          "type": "array",
          "default": [],
          "title": "The individual data item types referenced in plan",
          "items": {
            "$ref": "#/$defs/item"
          }
        },
        "graph": {
          "type": "array",
          "default": [],
          "title": "The array of entity types",
          "items": {
            "$ref": "#/$defs/entity"
          }
        },
        "lexicons": {
          "type": ["array", "null"],
          "title": "SDJ Description Lexicons associated with this description",
          "default": null,
          "items": {
            "type": "string"
          }
        },
        "lang": {
          "type": "string",
          "default": "en",
          "title": "The language of the text in the description/sdj",
          "examples": [
            "en"
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "sdInfo",
        "items",
        "graph"
      ]
    },
    "info": {
      "type": "object",
      "description": "Standardized set of values for name, uniqKey, created date, and last modified date",
      "properties": {
        "name": {
          "type": "string",
          "title": "Name of descriptor"
        },
        "uniqId": {
          "title": "Unique id for tracking, initialized on plan/data creation",
          "type": "string"
        },
        "created": {
          "title": "UTC Time descriptor was created",
          "type": "integer"
        },
        "modified": {
          "title": "UTC Time descriptor was last modified",
          "type": "integer"
        }
      },
      "required": ["name", "uniqId", "created", "modified"],
      "additionalProperties": false
    },
    "data": {
      "type": "object",
      "description": "Standardized expandable data object",
      "properties": {
        "sdKey": {
          "type": "string",
          "title": "Key id/name/route of data"
        },
        "sdId": {
          "title": "Entity sdId associated with data",
          "type": "integer"
        },
        "sdInfo": {
          "type": "object",
          "default": null,
          "title": "Optional descriptor object for tracking data changes",
          "items": {
            "$ref": "#/$defs/info"
          }
        },
        "sdChildren": {
          "title": "Child data array",
          "type": ["array", "null"],
          "default": null,
          "items": {
            "$ref": "#/$defs/data"
          }
        }
      },
      "required": ["sdKey", "sdId"],
      "additionalProperties": true
    },
    "entity": {
      "type": "object",
      "title": "Entity description of data as content/relationships",
      "properties": {
        "sdId": {
          "type": "integer",
          "title": "sdId of entity in description graph"
        },
        "sdKey": {
          "type": "string",
          "title": "sdKey for Entity"
        },
        "extendIds": {
          "type": ["array", "null"],
          "title": "Optional ids which current Entity extends",
          "default": null,
          "items": {
            "type": "integer",
            "title": "Extended entity ids",
            "uniqueItems": true
          }
        },
        "parentIds": {
          "type": ["array", "null"],
          "title": "Optional allowed entity's parent sdIds",
          "default": null,
          "items": {
            "type": "integer",
            "title": "Allowed parent entity ids",
            "uniqueItems": true
          }
        },
        "childIds": {
          "type": ["array", "null"],
          "title": "Optional allowed entity's children sdIds",
          "default": null,
          "items": {
            "type": "integer",
            "title": "Child entity id",
            "uniqueItems": true
          }
        },
        "sdItems": {
          "type": ["array", "null"],
          "default": null,
          "title": "Entity's associated item sdIds",
          "items": {
            "type": "integer",
            "title": "Entity's associated item sdId",
            "uniqueItems": true
          }
        },
        "limiter": {
          "type": ["string", "null"],
          "title": "Parallels to entity limiter, used for limitations",
          "default": null
        },
        "sdProps": {
          "type": ["object", "null"],
          "default": null,
          "title": "Extended assigned key/value props of entity",
          "additionalProperties": true
        },
        "dataInfo": {
          "type": ["boolean", "null"],
          "default": null,
          "title": "SDJ switch for uniqKey/creation/modification. If true systems will save and expect info per data object."
        }
      },
      "additionalProperties": false,
      "required": ["sdId", "sdKey"]
    },
    "item": {
      "title": "Describes a data item found in data object/entity",
      "type": "object",
      "properties": {
        "sdId": {
          "title": "sdId for item, used by entity",
          "type": "integer"
        },
        "sdKey": {
          "type": "string",
          "title": "sdKey property name found in data"
        },
        "type": {
          "type": "string",
          "title": "Type of data item"
        },
        "limiter": {
          "type": ["string", "null"],
          "title": "Parallels to entity limiter, used for limitations",
          "default": null
        }
      },
      "additionalProperties": false,
      "required": ["sdId", "sdKey", "type"]
    }
  }
}

=== willrudolph/sdj-esm/test/json/sdj/test-min-ang-lex-empty.json
{
  "$id": "http://willrudolph.com/schema/sdj-schema.json",
  "description": {
    "sdInfo": {
      "created": 1701390090598,
      "modified": 1701390090598,
      "name": "betadesc",
      "uniqId": "3rh28R-Qlbx4-i6Xy-gqB03Ac"
    },
    "lexicons": ["min-ang"],
    "graph": [],
    "items": [],
    "lang": "en"
  },
  "sdInfo": {
    "created": 1701390090598,
    "modified": 1701390090598,
    "name": "test-min-ang-lex-empty.json",
    "uniqId": "3rh28R-Qlbx4-i6Xy-gq103MA"
  },
  "data": []
}

=== willrudolph/sdj-esm/test/json/desc-test-a.json
{
  "$id": "http://willrudolph.com/schema/sdj-schema.json",
  "description": {
    "sdInfo": {
      "created": 1701390090598,
      "modified": 1701390090598,
      "name": "descName",
      "uniqId": "3rh28R-Qlbx4-i6Xy-gqB03MA"
    },
    "graph": [],
    "items": [],
    "lang": "en"
  },
  "sdInfo": {
    "created": 1701390090598,
    "modified": 1701390090598,
    "name": "desc-test-a.json",
    "uniqId": "4rh28R-Qlbx4-i6Xy-g3B03MA"
  },
  "data": []
}

=== willrudolph/sdj-esm/test/json/sdj/data/mini-db-test.json
{
  "$id": "http://willrudolph.com/schemas/sdj-schema.json",
  "description": {
    "lang": "en",
    "sdInfo": {
      "created": 1701390090598,
      "modified": 1701390090598,
      "name": "mini-db-users",
      "uniqId": "3rh2R7-Qlbx4-i6Xy-gqB03mA"
    },
    "graph": [
      {
        "sdId": 1,
        "sdKey": "productTable",
        "childIds": [2],
        "limiter": "key_idx",
        "sdProps": {"key_idx": 2}
      },
      {
        "sdId": 2,
        "sdKey": "product",
        "sdItems": [2 , 3],
        "parentIds": [0, 1],
        "childIds": [3]
      },
      {
        "sdId": 3,
        "sdKey": "categoryTable",
        "childIds": [4],
        "limiter": "key_idx",
        "sdProps": {"key_idx": 2}
      },
      {
        "sdId": 4,
        "sdKey": "category",
        "sdItems": [2, 3],
        "parentIds": [2]
      }
    ],
    "items": [
      {
        "sdId": 2,
        "sdKey": "keyIdx",
        "type": "numb",
        "limiter": "req"
      },
      {
        "sdId": 3,
        "sdKey": "description",
        "type": "strl"
      }
    ]
  },
  "sdInfo": {
    "created": 1701390090598,
    "modified": 1701390090598,
    "name": "testFileA",
    "uniqId": "3rh38R-Qlbx4-i6Xy-gq103MA"
  },
  "data": [{
    "sdId": 1,
    "sdKey": "home",
    "title": "Home",
    "sdChildren": [
      {
        "sdId": 2,
        "sdKey": "home_page1",
        "title": "Home Page 1",
        "sdChildren": [
          {
            "sdId": 2,
            "sdKey": "article1",
            "title": "Article 1"
          },
          {
            "sdId": 2,
            "sdKey": "article2",
            "title": "Article 2"
          },
          {
            "sdId": 2,
            "sdKey": "article3",
            "title": "Article 3"
          }
        ]
      },
      {
        "sdId": 2,
        "sdKey": "home_page2",
        "title": "Home Page 2",
        "sdChildren": [
          {
            "sdId": 3,
            "sdKey": "article1",
            "title": "Article 1"
          },
          {
            "sdId": 3,
            "sdKey": "article2",
            "title": "Article 2"
          },
          {
            "sdId": 3,
            "sdKey": "article3",
            "title": "Article 3"
          }
        ]
      },
      {
        "sdId": 2,
        "sdKey": "home_page3",
        "title": "Home Page 3",
        "sdChildren": [
          {
            "sdId": 3,
            "sdKey": "article1",
            "title": "Article 1"
          },
          {
            "sdId": 3,
            "sdKey": "article2",
            "title": "Article 2"
          },
          {
            "sdId": 3,
            "sdKey": "article3",
            "title": "Article 3"
          }
        ]
      }
    ]
  }]
}

=== willrudolph/sdj-esm/test/json/sdj/test-extends.json
{
  "$id": "http://willrudolph.com/schema/sdj-schema.json",
  "description": {
    "sdInfo": {
      "created": 1701390090598,
      "modified": 1701390090598,
      "name": "extends",
      "uniqId": "3rh28R-Qlbx4-i6Xy-gqB33Ac"
    },
    "graph": [
      {
        "sdId": 1,
        "sdKey": "alpha",
        "sdItems": [2, 3],
        "parentIds": [0],
        "sdProps": {
          "all": false,
          "bil": "name",
          "can": 3
        }
      },
      {
        "sdId": 2,
        "sdKey": "beta",
        "extendIds": [1],
        "sdItems": [4],
        "parentIds": [0],
        "sdProps": {
          "all": true,
          "jeb": 7
        }
      },
      {
        "sdId": 3,
        "sdKey": "gamma",
        "extendIds": [2],
        "sdItems": [5],
        "parentIds": [0]
      },
      {
        "sdId": 4,
        "sdKey": "delta",
        "extendIds": [3],
        "sdItems": [6],
        "parentIds": [0]
      },
      {
        "sdId": 5,
        "sdKey": "gamma_sub",
        "extendIds": [3],
        "sdItems": [7],
        "parentIds": [0],
        "sdProps": {
          "dad": 32
        }
      },
      {
        "sdId": 6,
        "sdKey": "beta_and_gamma_sub",
        "extendIds": [2, 5],
        "sdItems": [8],
        "parentIds": [0],
        "sdProps": {
          "jeb": 2,
          "all": 4
        }
      }
    ],
    "items": [
      {
        "sdId": 2,
        "sdKey": "title",
        "type": "string",
        "limiter": "req"
      },
      {
        "sdId": 3,
        "sdKey": "keyName3",
        "type": "strl"
      },
      {
        "sdId": 4,
        "sdKey": "keyName4",
        "type": "numb"
      },
      {
        "sdId": 5,
        "sdKey": "keyName5",
        "type": "numb"
      },
      {
        "sdId": 6,
        "sdKey":"keyName6",
        "type": "strl"
      },
      {
        "sdId": 7,
        "sdKey": "keyName7",
        "type": "numb"
      },
      {
        "sdId": 8,
        "sdKey": "keyName8",
        "type": "numb"
      }
    ],
    "lang": "en"
  },
  "sdInfo": {
    "created": 1701390090598,
    "modified": 1701390090598,
    "name": "test-extends.json",
    "uniqId": "3rh28R-Qlbx4-i6Xy-gq103MA"
  },
  "data": [
    {
      "sdId": 1,
      "sdKey": "home1",
      "title": "Home1"
    },
    {
      "sdId": 2,
      "sdKey": "home2",
      "title": "Home2"
    },
    {
      "sdId": 3,
      "sdKey": "home3",
      "title": "Home3"
    },
    {
      "sdId": 4,
      "sdKey": "home4",
      "title": "Home4"
    },
    {
      "sdId": 5,
      "sdKey": "home5",
      "title": "Home5"
    },
    {
      "sdId": 6,
      "sdKey": "home6",
      "title": "Home6"
    }
  ]
}

=== willrudolph/sdj-esm/test/json/sdj/example-simple-lex.json
{
  "$id": "http://willrudolph.com/schemas/sdj-schema.json",
  "description": {
    "sdInfo": {
      "created": 1701390090598,
      "modified": 1701390090598,
      "name": "simple-lex",
      "uniqId": "3rh28R-Qlbx4-i6Xy-gqB03Ac"
    },
    "lexicons": ["simple"],
    "graph": [],
    "items": [],
    "lang": "en"
  },
  "sdInfo": {
    "created": 1701390090598,
    "modified": 1701390090598,
    "name": "simpleLexicon",
    "uniqId": "3rh28R-Qlbx4-i6Xy-gq103MA"
  },
  "data": [{
      "sdId": 2,
      "sdKey": "home",
      "routeTitle": "Home",
      "compClassName": "HomeComponent",
      "sdChildren": [
        {
          "sdId": 1,
          "sdKey": "home_comp1",
          "compClassName": "SubHomeComp",
          "sdChildren": [
            {
              "sdId": 3,
              "sdKey": "article1",
              "title": "Article 1"
            },
            {
              "sdId": 3,
              "sdKey": "article2",
              "title": "Article 2"
            },
            {
              "sdId": 3,
              "sdKey": "article3",
              "title": "Article 3"
            }
          ]
        },
        {
          "sdId": 1,
          "sdKey": "home_page2",
          "compClassName": "SubHomeComp",
          "sdChildren": [
            {
              "sdId": 3,
              "sdKey": "article1",
              "title": "Article 1"
            },
            {
              "sdId": 3,
              "sdKey": "article2",
              "title": "Article 2"
            },
            {
              "sdId": 3,
              "sdKey": "article3",
              "title": "Article 3"
            }
          ]
        },
        {
          "sdId": 2,
          "sdKey": "home_page3",
          "compClassName": "SubHomeComp",
          "sdChildren": [
            {
              "sdId": 3,
              "sdKey": "article1",
              "title": "Article 1"
            },
            {
              "sdId": 3,
              "sdKey": "article2",
              "title": "Article 2"
            },
            {
              "sdId": 3,
              "sdKey": "article3",
              "title": "Article 3"
            }
          ]
        }
      ]
    },
    {
      "sdId": 2,
      "sdKey": "projects",
      "routeTitle": "Projects",
      "compClassName": "HomeComponent",
      "sdChildren": [
        {
          "sdId": 2,
          "sdKey": "alpha_project",
          "routeTitle": "Alpha Project",
          "compClassName": "SubHomeComp",
          "sdChildren": [
            {
              "sdId": 3,
              "sdKey": "article1",
              "title": "Article 1"
            },
            {
              "sdId": 3,
              "sdKey": "article2",
              "title": "Article 2"
            },
            {
              "sdId": 3,
              "sdKey": "article3",
              "title": "Article 3"
            }
          ]
        },
        {
          "sdId": 2,
          "sdKey": "beta_project",
          "compClassName": "SubHomeComp",
          "routeTitle": "Beta Project",
          "sdChildren": [
            {
              "sdId": 3,
              "sdKey": "article1",
              "title": "Article 1"
            },
            {
              "sdId": 3,
              "sdKey": "article2",
              "title": "Article 2"
            },
            {
              "sdId": 3,
              "sdKey": "article3",
              "title": "Article 3"
            }
          ]
        },
        {
          "sdId": 2,
          "sdKey": "gamma_project",
          "compClassName": "SubHomeComp",
          "sdChildren": [
            {
              "sdId": 3,
              "sdKey": "article1",
              "title": "Article 1"
            },
            {
              "sdId": 3,
              "sdKey": "article2",
              "title": "Article 2"
            },
            {
              "sdId": 3,
              "sdKey": "article3",
              "title": "Article 3"
            }
          ]
        }
      ]
    },
    {
      "sdId": 2,
      "sdKey": "resume",
      "routeTitle": "Resume",
      "compClassName": "HomeComponent",
      "sdChildren": [{
        "sdId": 3,
        "sdKey": "article1",
        "title": "Article 1"
      },
      {
        "sdId": 3,
        "sdKey": "article2",
        "title": "Article 2"
      },
      {
        "sdId": 3,
        "sdKey": "article3",
        "title": "Article 3"
      }
    ]
    },
    {
      "sdId": 2,
      "sdKey": "contact",
      "routeTitle": "Contact",
      "compClassName": "HomeComponent",
      "sdChildren": [{
        "sdId": 1,
        "compClassName": "ContactSubComponent",
        "sdKey": "article1",
        "title": "Article 1"
        },
        {
          "sdId": 3,
          "sdKey": "article2",
          "title": "Article 2"
        },
        {
          "sdId": 3,
          "sdKey": "article3",
          "title": "Article 3"
        }
      ]
    }]
}

=== willrudolph/sdj-esm/test/json/sdj-empty-good.json
{
  "$id": "http://willrudolph.com/schema/sdj-schema.json",
  "description": {
    "sdInfo": {
      "created": 1701390090598,
      "modified": 1701390090598,
      "name": "descName",
      "uniqId": "3rh28R-Qlbx4-i6Xy-gqB03MA"
    },
    "graph": [{
      "sdId": 1,
      "sdKey": "dataEnt",
      "sdItems": [2]
    }],
    "items": [{
      "sdId": 2,
      "sdKey": "someValue",
      "type": "strd"
    }],
    "lang": "en"
  },
  "sdInfo": {
    "created": 1701390090598,
    "modified": 1701390090598,
    "name": "sdj-empty-good.json",
    "uniqId": "4rh28R-Qlbx4-i6Xy-g3B03MA"
  },
  "data": []
}

=== willrudolph/sdj-esm/test/json/entity-test-a.json
{
  "$id": "http://willrudolph.com/schema/sdj-schema.json",
  "description": {
    "sdInfo": {
      "created": 1701390090598,
      "modified": 1701390090598,
      "name": "descName",
      "uniqId": "3rh28R-Qlbx4-i6Xy-gqB03MA"
    },
    "graph": [{
        "sdId": 1,
        "sdKey": "table",
        "limiter": "sdj_index",
        "parentIds": [0],
        "childIds": [2]
      },
      {
        "sdId": 2,
        "sdKey": "tableRow",
        "parentIds": [1],
        "sdItems": [2, 3]
      },
      {
        "sdId": 3,
        "sdKey": "otherEnt",
        "parentIds": [0],
        "sdItems": [4]
      }
    ],
    "items": [
      {
        "sdId": 2,
        "sdKey": "tableRowValue01",
        "limiter": "req",
        "type": "string"
      },
      {
        "sdId": 3,
        "sdKey": "tableRowValue02",
        "limiter": "req",
        "type": "numb"
      },
      {
        "sdId": 4,
        "sdKey": "firstTable",
        "type": "sdindex"
      }
    ],
    "lang": "en"
  },
  "sdInfo": {
    "created": 1701390090598,
    "modified": 1701390090598,
    "name": "entity-test-a.json",
    "uniqId": "4rh28R-Qlbx4-i6Xy-g3B03MA"
  },
  "data": [
    {
      "sdKey": "firstTable",
      "sdId": 1,
      "subChildren": [
        {
          "sdKey": "sdIndex0",
          "sdId": 2,
          "tableRowValue01": "sadfasf",
          "tableRowValue02": 22
        },
        {
          "sdKey": "sdIndex1",
          "sdId": 2,
          "tableRowValue01": "sadfasf",
          "tableRowValue02": 22
        },
        {
          "sdKey": "sdIndex2",
          "sdId": 2,
          "tableRowValue01": "sadfasf",
          "tableRowValue02": 22
        }
      ]
    },
    {
      "sdKey": "otherData",
      "sdId": 3,
      "firstTable": 0
    }
  ]
}

=== willrudolph/sdj-esm/test/json/sdj-blank-good.json
{
  "$id": "http://willrudolph.com/schema/sdj-schema.json",
  "description": {
    "sdInfo": {
      "created": 0,
      "modified": 0,
      "name": "descName",
      "uniqId": "000000-00000-0000-0000000"
    },
    "graph": [],
    "items": []
  },
  "sdInfo": {
    "created": 1701390090598,
    "modified": 1701390090598,
    "name": "sdj-blank-good.json",
    "uniqId": "000000-00000-0000-0000000"
  },
  "data": []
}
